<?php
/*
 * Canonical maintenance-inspection section definitions.
 * Single source of truth used by employee_visit.php, maintenance_form.php
 * and faults.php. Each section maps field keys → human labels.
 *
 * Usage:  $form_sections = require __DIR__ . '/form_sections.php';
 */
return [
    'equipment' => [
        'label' => 'Equipment Inspection Checklist',
        'fields' => [
            'seals_condition'             => 'Seals Condition',
            'power_port_fibres'           => 'Power Port Fibres',
            'radio_unit_antenna'          => 'Radio Unit & Antenna',
            'if_cable'                    => 'IF Cable',
            'mounting_kit_screws'         => 'Mounting Kit Screws',
            'state_of_fans'               => 'State of Fans',
            'presence_of_dust'            => 'Presence of Dust',
            'surface_of_cabinet'          => 'Surface of Cabinet',
            'lock_condition'              => 'Lock Condition',
            'cabinet_cleanliness'         => 'Cabinet Cleanliness',
            'led_status'                  => 'LED Status',
            'power_cables_connections'    => 'Power Cables & Connections',
            'acdb_voltage_readings'       => 'ACDB Voltage Readings',
            'ground_cable_grounding_bar'  => 'Ground Cable & Grounding Bar',
            'battery_voltage_connections' => 'Battery Voltage & Connections',
            'power_supply_alarms'         => 'Power Supply Alarms',
            'air_conditioner'             => 'Air Conditioner',
            'overall_tower_condition'     => 'Overall Tower Condition',
            'fencing_condition'           => 'Fencing Condition',
        ],
    ],
    'generator' => [
        'label' => 'Generator Inspection',
        'fields' => [
            'generator_status'        => 'Generator Status',
            'condition_batteries'     => 'Condition of Batteries',
            'electrolyte_condition'   => 'Electrolyte Condition',
            'battery_terminals'       => 'Battery Terminals',
            'battery_charger'         => 'Battery Charger',
            'control_panel_condition' => 'Control Panel Condition',
            'component_condition'     => 'Component Condition',
            'indicating_bulbs'        => 'Indicating Bulbs',
            'selector_switches'       => 'Selector Switches',
            'circuit_breakers'        => 'Circuit Breakers',
            'fuse_holders'            => 'Fuse Holders',
            'fuse_links'              => 'Fuse Links',
            'electrical_connections'  => 'Electrical Connections',
            'operation_meters'        => 'Operation Meters',
            'timing_devices'          => 'Timing Devices',
            'lovato_relay'            => 'Lovato Relay',
        ],
    ],
    'transmission' => [
        'label' => 'Transmission & Power Checks',
        'fields' => [
            'microwave_link'      => 'Microwave Link',
            'cell_availability'   => 'Cell Availability',
            'bbu_interface'       => 'BBU Interface',
            'rtn'                 => 'RTN',
            'alarm_status'        => 'Alarm Status',
            'temp_control_system' => 'Temperature Control System',
            'power_cable'         => 'Power Cable',
            'smu'                 => 'SMU',
            'fiber'               => 'Fiber',
            'housekeeping'        => 'Housekeeping',
            'main_breaker'        => 'Main Breaker',
            'earth_leakage'       => 'Earth Leakage',
        ],
    ],
    'security' => [
        'label' => 'Site Security & Civil Works',
        'fields' => [
            'fence_locks'            => 'Fence and Locks',
            'possible_forced_entry'  => 'Possible Forced Entry',
            'terrain_water_drainage' => 'Terrain Water Drainage',
            'apron_condition'        => 'Apron Condition',
            'rubbish_free_area'      => 'Rubbish-Free Area',
            'aviation_light'         => 'Aviation Light',
            'fence_controller'       => 'Fence Controller',
            'fumigation'             => 'Fumigation',
            'manholes'               => 'Manholes',
            'intrusion_alarms'       => 'Intrusion Alarms',
            'cable_trays'            => 'Cable Trays',
            'paintwork'              => 'Paintwork',
            'physical_damage'        => 'Physical Damage',
            'locks_hinges'           => 'Locks & Hinges',
        ],
    ],
    'container' => [
        'label' => 'Container Inspection',
        'fields' => [
            'container_feet'       => 'Container Feet',
            'container_frame_feet' => 'Container Frame Feet',
            'door_seals'           => 'Door Seals',
            'ingress_water_dust'   => 'Water / Dust Ingress',
            'container_openings'   => 'Container Openings',
            'cable_breakages'      => 'Cable Breakages',
            'cable_overheating'    => 'Cable Overheating',
        ],
    ],
    'electrical' => [
        'label' => 'Electrical Safety',
        'fields' => [
            'earth_connections'   => 'Earth Connections',
            'stubs'               => 'Stubs',
            'feeders'             => 'Feeders',
            'cabinets_earthed'    => 'Cabinets Earthed',
            'labelling'           => 'Labelling',
            'rcd_elcb'            => 'RCD / ELCB',
            'phase_phase_voltage' => 'Phase-to-Phase Voltage',
            'phase_earth_voltage' => 'Phase-to-Earth Voltage',
            'earth_leakage_elec'  => 'Earth Leakage',
            'lightning_protector' => 'Lightning Protector',
            'surge_arrestors'     => 'Surge Arrestors',
            'exposed_conductors'  => 'Exposed Conductors',
            'ats_status'          => 'ATS Status',
        ],
    ],
];
